2024-12-22 14:09:52.133 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/automations/notifications/severe_weather_alert.yaml contains duplicate key "platform". Check lines 8 and 10
2024-12-22 14:09:52.328 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration presence_simulation which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-22 14:09:52.330 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration iphonedetect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-22 14:09:52.332 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pirateweather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-22 14:09:52.334 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-22 14:09:52.335 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration simple_wyze_vac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-22 14:09:52.338 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-22 14:09:52.340 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nws_alerts which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-22 14:09:52.342 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration gasbuddy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-22 14:09:52.344 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration reolink_discovery which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-22 14:09:52.347 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration wyzeapi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-22 14:09:52.349 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration auto_backup which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-22 14:10:08.437 ERROR (MainThread) [pyatv.protocols.companion] Could not fetch SystemStatus, power_state will not work (Command failed: No request handler)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pyatv/protocols/companion/__init__.py", line 219, in initialize
    system_status = await self.api.fetch_attention_state()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyatv/protocols/companion/api.py", line 439, in fetch_attention_state
    resp = await self._send_command("FetchAttentionState", {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyatv/protocols/companion/api.py", line 172, in _send_command
    resp = await self._protocol.exchange_opack(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/pyatv/protocols/companion/protocol.py", line 153, in exchange_opack
    return await self._exchange_generic_opack(frame_type, data, identifier, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyatv/protocols/companion/protocol.py", line 174, in _exchange_generic_opack
    raise exceptions.ProtocolError(f"Command failed: {unpacked_object['_em']}")
pyatv.exceptions.ProtocolError: Command failed: No request handler
2024-12-22 14:10:19.489 ERROR (MainThread) [homeassistant.components.sensor] Platform smartthings does not generate unique IDs. ID 1a6d0984-19b4-426e-86d8-77906f2fe112.energy already exists - ignoring sensor.outlet_energy_meter
2024-12-22 14:10:19.489 ERROR (MainThread) [homeassistant.components.sensor] Platform smartthings does not generate unique IDs. ID 1a6d0984-19b4-426e-86d8-77906f2fe112.power already exists - ignoring sensor.outlet_power_meter
2024-12-22 14:10:32.178 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error initializing 'Low Level Notifications' trigger: In 'numeric_state' condition: unknown entity sensor.southeast_corner_battery
2024-12-22 14:10:32.179 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error initializing 'Low Level Notifications' trigger: In 'numeric_state' condition: unknown entity sensor.backyard_east_battery
2024-12-22 14:10:32.180 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error initializing 'Low Level Notifications' trigger: In 'numeric_state' condition: unknown entity sensor.backyard_west_battery
